### ISSUE TITLE
another way to solve issue

### ISSUE THREAD

**Issue by tdeheurles** [justingrayston/kubernetes-docker-dns#2]
hi,
Just as an information, I had the same issue today.

I followed [that same issue](https://gist.github.com/guybrush/47bcd5f4e41a3be102b2).
The fix was to add `-kube_master_url=http://__API-SERVER__:__API-SERVER-PORT__` with the good alement at each one.

**Comment by justingrayston** [comment]
@tdeheurles - thanks, but I think that relates to kube2sky image and not being able to connect to the API server, this shouldn't be an issue with this set up. For me it finds the server just fine, the problems seems to be the creation of the Endpoints for the services. Well that what it looks like to me, as they get Deleted right after being created looking at the log output.

**Comment by tdeheurles** [comment]
ok. Thanks for return.

Setting up everything from scratch is a bit ... `complicated` ^^
