### ISSUE TITLE
Change to .yml extension not yaml

### ISSUE THREAD

**Issue by justingrayston** [justingrayston/kubernetes-docker-dns#8]

**Comment by gauravspatel** [comment]
The official FAQ for yaml says otherwise: http://www.yaml.org/faq.html

**Comment by justingrayston** [comment]
Yup, I have used .yaml for years, but if you look around the Kubernetes code base you will see yml. I think what prompted me to add this was a warning come up somewhere.

I think it is something todo with windows users worrying about file extensions longer than 3 characters and being consistent across platforms.

**Comment by gauravspatel** [comment]
That's a tough one.  Kubernetes is pretty inconsistent in their usage of .yml vs .yaml.  The rc + service you pulled are .yaml.in in their repo (https://github.com/kubernetes/kubernetes/tree/release-1.1/cluster/addons/dns).  Some counter-examples for .yml in their repo (https://github.com/kubernetes/kubernetes/blob/release-1.1/shippable.yml).

There isn't a problem in Windows for longer than 3 letter suffixes (.java being a good example).

Your repo helped me get skydns working locally on my local setup...I owe you a pull request for something.  If you still want this, I can get something back to you that moves it all to .yml.

**Comment by justingrayston** [comment]
To be honest, I agree with you. I am trying to rack my memory to what exactly threw the warning. It was a line in terminal output at somepoint which sounded like it was a suggested "convention" in kuberland, so I added this. The yaml.in I think is to denote that they are templates, but you are correct they are most definitely yaml.

I am going to close and reopen if I see the warning again and then mention it in the issue like I should have done in the first place.

Glad you the repo helpful :)
