### ISSUE TITLE
DNS doesn't not work

### ISSUE THREAD

**Issue by kurakin-oleksandr** [justingrayston/kubernetes-docker-dns#9]
I get errors during starting DNS in kube2sky pod:

`kubectl logs --namespace=kube-system kube-dns-v9-xajqs kube2sky`
Failed to list *api.Endpoints: couldn't get version/kind; json parse error: invalid character '<' looking for beginning of value
Failed to list *api.Service: couldn't get version/kind; json parse error: invalid character '<' looking for beginning of value

I launched this scripts on Ubuntu 14.04 not on OSX.

**Comment by kurakin-oleksandr** [comment]
~~I just switched to official kubernetes v1.1.2 and seems everything works good~~

**Comment by justingrayston** [comment]
Do you still have this issue? It was that issue that led me to create this funnily enough. I have raised #10 and will update the images later today. I don't see why Ubuntu would impact something running in a container. Once I have updated the images (I already have a project using the latest and works ok), I will update here, could you then test please?

**Comment by kurakin-oleksandr** [comment]
Hello. Yes, I still have this issue. I'm waiting your updates to test :)

**Comment by justingrayston** [comment]
@kurakin-oleksandr 

Please checkout feature/update_images branch. Works for me on my Mac, here is the log output of the healthz checking the lookup is working.

Let me know how you get on. If ok I will merge pull #11 

Thanks

```
md nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:01 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:03 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:05 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:08 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:09 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:11 Client ip 172.17.0.1:51671 requesting /healthz probe servicing cmd nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:11 Client ip 172.17.0.1:51672 requesting /healthz probe servicing cmd nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:12 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:13 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:15 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:17 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:19 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:21 Client ip 172.17.0.1:51685 requesting /healthz probe servicing cmd nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:21 Client ip 172.17.0.1:51686 requesting /healthz probe servicing cmd nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:21 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:24 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
2015/12/09 20:51:25 Worker running nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
```

**Comment by kurakin-oleksandr** [comment]
It doesn't help. I've same problem. Logs from healthz:

`2015/12/09 21:24:36 Client ip 172.17.0.1:50177 requesting /healthz probe servicing cmd nslookup kubernetes.default.svc.cluster.local localhost >/dev/null`

`2015/12/09 21:24:36 Healthz probe error: Result of last exec: nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
, at 2015-12-09 21:24:35.054405351 +0000 UTC, error exit status 1`

**Comment by justingrayston** [comment]
Ah - here's a thought. Did you up update config.sh to change the IP where your kubernetes api endpoint is?

For me, because I am running Docker in the VM it is:

```
export KUBE_SERVER=http:\\/\\/192.168.99.100:8080
```

Which is the IP of my endpoint for the containers (kube2sky in particulary) to talk to the kubemaster.

So, as you are running on Linux anyway, isn't your api available on 127.0.0.1:8080?

**Comment by kurakin-oleksandr** [comment]
Yes, sure. I use 0.0.0.0 but it's same as 127.0.0.1

**Comment by justingrayston** [comment]
So you have changed the KUBE_SERVER value to that and run ./setup_dns.sh and restarted the dns replication controller, and it still doesn't work? Actually that may make sense because it may actually think it is local to the container itself.

If you exec into the kube2sky container and you wget http://0.0.0.0:8080 do you get the root api response?

If not what if you set up a host entry on your machine?

```
0.0.0.0 kube.api
```

Then use that in the KUBE_SERVER?

**Comment by kurakin-oleksandr** [comment]
You're right. It fetches response from wrong server:
`<b> Kubernetes healthz sidecar container </b><br/><br/><a href="/healthz">/healthz: healthz probe. Returns "ok" if the command given through -cmd exits with 0.</a><br/><a href="/quit">/quit: Cause this container to exit.</a><br/>`

**Comment by kurakin-oleksandr** [comment]
I use another IP (172.17.0.1 - looks like it's docker's). DNS container run!

kubectl exec busybox -ti nslookup kubernetes
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      kubernetes
Address 1: 10.0.0.1

Bingo!

Thank you, @justingrayston

**Comment by justingrayston** [comment]
Great. I have created #12 to make the Readme clearer. Thanks.
